### ISSUE TITLE
Run test CIs with a known version of MeiliSearch

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#115]
Currently, our test CIs containing integration tests run against `meilisearch:latest` which is the latest stable version of MeiliSearch in DockerHub.

This `meilisearch:latest` brings many interests:
- it avoids the integration team updating the version in all the CIs (we have a LOT of repos) for each MeiliSearch release.
- thanks to this `meilisearch:latest` we were able to see immediately bugs in MeiliSearch at the early beginning of the release. It helped a lot the core-team to quickly fix the bugs.

Cons:
- we cannot control the MeiliSearch version when we run tests -> we completely depend on the MeiliSearch release. It leads to some inconsistencies (bad timings) when trying to merge PRs just because the MeiliSearch release is out during the merge.

Because of this con, and more in general, we need to remove the `meilisearch:latest` for a `meilisearch:vX.X.X` so that we can **control the environment of our CIs**.
However, the pros are still valuable for the integration team and even for Meili teams in general. We need to be sure the pros are still present in other ways before applying this change in our CIs.

### Solutions

For the first point, the maintenance, I can add this change in the [pre-release week script](https://github.com/meilisearch/integration-scripts/tree/main/pre-release-script) (internal only).

For the second point, the track of the bugs, I should create a CI launching all the SDKs tests every week, or manually on the MeiliSearch side. I need to define with the rest of the core team how to handle this! I will create an issue about this in the MeiliSearch's repo, probably after the v0.21.0 is out (sorry for the delay).

Once these two issues are fixed, we will be able to remove `meilisearch:latest` 😁

**Comment by bidoubiwa** [comment]
> For the first point, the maintenance, I can add this change in the pre-release week script (internal only).

I'm not sure I understand, are you suggesting the following: 
In each `bump-meilisearch-$new_version` you change the version of MeiliSearch in the  `test.yml`  using something like the nice script you made [generic-file-updatr](https://github.com/meilisearch/integration-scripts/tree/main/generic-files-updater)?

Additionnaly we could also try to make the `test.yaml` as similar as possible between each SDK's (jobs name, file names, ..) and then potentially add a strategy matrix ([example here](https://github.com/meilisearch/meilisearch-js/blob/main/.github/workflows/tests.yml))? 

```yaml
docker run -d -p 7700:7700 getmeili/meilisearch:${{ matrix.meilisearch }}
```

context example:

```yaml
   strategy:
      matrix:
        meilisearch: [ '0.20.0', '0.21.1' ]
   [...]
      steps:
           [...]
           - name: MeiliSearch (latest) setup with Docker
           run: docker run -d -p 7700:7700 getmeili/meilisearch:${{ matrix.meilisearch }} ./meilisearch --no-analytics=true --master-key='masterKey'
```

Also, not sure what is issue one and what is issue two.
