### ISSUE TITLE
Add Docker/Docker-Compose configuration to every integration

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/integration-guides#199]
The idea is to create a standard way to use docker in the integration team's repositories.

The implementation should contain at least*:

- A service called `meilisearch` of course!
- A service called `package` (this name is not defined yet, some options, `lib`, `src`, `package`, `repo`, `app`, `source`, `sdk`, `integration`, needs to work for every integration). 
   - In the main service we should have links to the `meilisearch` service, to be possible to access `http://meilisearch:7700`.
   - We should be able to avoid downloading multiple times the same dependency, volumes could prevent it.
- The `meilisearch` service should point to `latest` tag.
- The `meilisearch` service should have `environment` item `- MEILI_NO_ANALYTICS="true"` 
- The base image should be based on only one distro, `debian/ubuntu`.
- The code of the SDK must respect an environment flag with the host of meilisearch could be eg. `MEILISEARCH_HOST`, `MEILISEARCH_URL` and not define directly `localhost:7700` as usual.
- If the code relies on an API KEY, you can define the environment flag as `MEILISEARCH_API_KEY`.
- If the setup requires a docker entry point it should be called `docker-entrypoint.sh`.

<details>
  <summary>Click to see an example for the ruby SDK</summary>
  
   ```yml
   version: "3.8"

   volumes:
     bundle:

   services:
     package:
       image: ruby:3.0
       tty: true
       stdin_open: true
       working_dir: /home/package
       environment:
         - MEILISEARCH_HOST=meilisearch
         - MEILISEARCH_PORT=7700
         - BUNDLE_PATH=/vendor/bundle
       volumes:
         - ./:/home/package
         - bundle:/vendor/bundle
       links:
         - meilisearch

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
   ```
</details>

### How do we prevent container name conflicts?
```
Error response from daemon: Conflict. The container name "/meilisearch" is already in use by container "a5aa500212bd3325a6d8a0099c7a750c292661850b640a5b140b7369cccac051". You have to remove (or rename) that container to be able to reuse that name.
```
Re) Remove all the `container_name` from the `meilisearch` service and add the `links: ['meilisearch']` to the `package` service.

### How do we prevent port conflicts?
```
Error response from daemon: driver failed programming external connectivity on endpoint meilisearch (4af35bd1b1b9c7df119a01470c4d91dcbe02c3f4dd73b6b8df142ec94f02b988): Bind for 0.0.0.0:7700 failed: port is already allocated
```

Re) Just use `ports: ['7700']` without caring with both in and out like `ports: ['7700:7700']`

### Is possible to have only one `meilisearch` instance running?

Also, this is a good thing, or it could lead to other bugs?

*PS: The `docker-compose` could have more services, but these two are required.

**Comment by brunoocasali** [comment]
> Is possible to have only one meilisearch instance running?

About this idea, I don't think it is a good idea because if we are running the same instance we will probably have unintentional changes like dropping the data or running a test with a different test setup and so on...

In the last update I made to the issue description I added the new sample in the ruby SDK, and I could solve the questions raised before, so I think we can skip this concern and just use it.

**Comment by brunoocasali** [comment]
In an internal meeting with @alallema and @bidoubiwa we decided that it could be helpful for newcomers to have a simple all-in-one command that shows us how to use it with docker.

So, every repo should add this sentence:


You can set up your local environment natively or using `docker`, check out the [`docker-compose.yml`](/docker-compose.yml).

Example of running all the checks with docker:
```bash
docker-compose run --rm package bundle install && bundle exec rspec && bundle exec rubocop
```

**Comment by alallema** [comment]
> Update 1st Jun:
> 
> I noticed I missed these two points today in our meeting.
> 
> **- The base image should be based on only one distro, debian/ubuntu.** I've opted to use debian/ubuntu based images because they are easier to find resources and maintain, if we notice the extra space they require is too much, we can move to `alpine` in the future.
> 
> **- If the setup requires a docker entry point it should be called `docker-entrypoint.sh`.** This is just a naming decision, no specific reason for that.
> 
> @alallema and @bidoubiwa do you agree with that?

I agree with the name of the `docker-entrypoint.sh`, but why do we have to use the same distro? According to the SDK there can be very practical ready-made images like the one of [composer](https://hub.docker.com/_/composer) for php.

**Comment by bidoubiwa** [comment]
I agree with amelie! There are some ready images that would avoid having to install some package managers if they are not natively on debian/ubuntu.

**Comment by brunoocasali** [comment]
It was just a misunderstanding, the idea is always adopt the `debian` based image for the language we will use in the docker like this: `node:current-buster` not this `node:current-alpine`.

**Comment by bidoubiwa** [comment]
About the docker compose, should we test them in our CI ? I have added this in the tests.yml of meilisearch-js

```yml
  docker_compose_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run docker
        run: docker-compose run --rm package bash -c "yarn install && yarn test && yarn lint"
```
